# Generated by Django 4.0.3 on 2022-10-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Timestamp', models.DateTimeField(blank=True)),
                ('description', models.CharField(max_length=250)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('favorite', models.BooleanField(default=0)),
                ('Tag', models.CharField(choices=[('Web_Development', 'Web_Development'), ('Machine_learning', 'Web_Development'), ('Technology', 'Technology'), ('Movies', 'Movies'), ('News', 'News'), ('Science', 'Science'), ('Music', 'Music'), ('Business', 'Business'), ('Cooking', 'Cooking'), ('Sports', 'Sports')], default='Web_Development', max_length=50)),
                ('upload_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
