# Generated by Django 4.0.3 on 2022-10-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='likes',
        ),
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.CharField(choices=[('FA', 'Film & Animation'), ('AV', 'Autos & Vehicles'), ('M', 'Music'), ('PA', 'Pets & Animals'), ('S', 'Sports'), ('TE', 'Travel & Events'), ('G', 'Gaming'), ('PB', 'People & Blogs'), ('C', 'Comedy'), ('En', 'Entertainment'), ('NP', 'News & Politics'), ('HS', 'Howto & Style'), ('Ed', 'Education'), ('ST', 'Science & Technology'), ('NA', 'Nonprofits & Activism')], default='PB', max_length=2),
        ),
        migrations.AddField(
            model_name='upload',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='favourite',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=200)),
                ('is_verfied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
