# Generated by Django 4.0.3 on 2022-10-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_upload_upload_author_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='favourite',
            new_name='favorite',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='category',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title',
        ),
        migrations.AddField(
            model_name='upload',
            name='Tag',
            field=models.CharField(choices=[('FA', 'Film & Animation'), ('AV', 'Autos & Vehicles'), ('M', 'Music'), ('PA', 'Pets & Animals'), ('S', 'Sports'), ('TE', 'Travel & Events'), ('G', 'Gaming'), ('PB', 'People & Blogs'), ('C', 'Comedy'), ('En', 'Entertainment'), ('NP', 'News & Politics'), ('HS', 'Howto & Style'), ('Ed', 'Education'), ('ST', 'Science & Technology'), ('NA', 'Nonprofits & Activism')], default='Web_Development', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='Title',
            field=models.CharField(default='type here', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
