# Generated by Django 4.0.3 on 2022-10-28 12:09

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_favourite_upload_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/new.png', upload_to='videos/', validators=[home.validators.fileSize]),
        ),
    ]
