# Generated by Django 4.1.2 on 2022-10-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_upload_timestamp_alter_upload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="Timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
