# Generated by Django 4.0.3 on 2022-10-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_upload_timestamp_alter_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Issue', models.TextField()),
                ('query_related', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=100)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
