# Generated by Django 4.1.2 on 2022-10-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_upload_timestamp"),
        ("home", "0008_contact_alter_upload_timestamp"),
    ]

    operations = []
