# Generated by Django 4.1.2 on 2022-10-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_merge_20221030_1814"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="private",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="upload",
            name="Tag",
            field=models.CharField(
                choices=[
                    ("Film & Animation", "Film & Animation"),
                    ("Autos & Vehicles", "Autos & Vehicles"),
                    ("Music", "Music"),
                    ("Pets & Animals", "Pets & Animals"),
                    ("Sports", "Sports"),
                    ("Travel & Events", "Travel & Events"),
                    ("Gaming", "Gaming"),
                    ("People & Blogs", "People & Blogs"),
                    ("Comedy", "Comedy"),
                    ("Entertainment", "Entertainment"),
                    ("News & Politics", "News & Politics"),
                    ("Howto & Style", "Howto & Style"),
                    ("Education", "Education"),
                    ("Science & Technology", "Science & Technology"),
                    ("Nonprofits & Activism", "Nonprofits & Activism"),
                ],
                default="Web_Development",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="Title",
            field=models.CharField(max_length=100),
        ),
    ]
