# Generated by Django 4.1.2 on 2022-10-31 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rename_favorite_upload_isfav_remove_upload_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="postId",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100000,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
