# Generated by Django 4.1.2 on 2022-10-31 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_upload_postid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="postId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
