# Generated by Django 4.1.2 on 2022-10-31 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0014_alter_upload_postid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="isfav",
        ),
        migrations.AddField(
            model_name="upload",
            name="favorite",
            field=models.ManyToManyField(
                blank=True, related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
