# Generated by Django 4.1.2 on 2022-10-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_remove_upload_isfav_upload_favorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="favorite",
        ),
        migrations.AddField(
            model_name="upload",
            name="isfav",
            field=models.BooleanField(default=0),
        ),
    ]
