# Generated by Django 4.1.2 on 2023-07-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_upload_favorite_upload_isfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='format',
            field=models.CharField(default='video', max_length=10),
        ),
    ]
