# Generated by Django 4.1.2 on 2022-11-01 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0016_remove_upload_favorite_upload_isfav"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("Name", models.CharField(default="New Playlist", max_length=30)),
                ("description", models.CharField(default="", max_length=100)),
                (
                    "playId",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                (
                    "list_post",
                    models.ManyToManyField(related_name="playlist", to="home.upload"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
