# Generated by Django 4.1.2 on 2022-11-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="playId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
